site_name: 纷云开发者文档
site_url: https://api.lesschat.com
repo_url: https://github.com/lesschat/docs
repo_name: GitHub
site_favicon: favicon.ico
site_description: 纷云开发者文档
site_author: yctech
copyright:  'Copyright&copy;2015 纷云'
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
include_next_prev: false
pages:
- [index.md, '快速开始']
- [api.md, API]

- [api/incoming.md, '接入API', 'Incoming Webhook']
- [api/outgoing.md, '接入API', 'Outgoing Webhook']
- [api/remote.md, '接入API', '远程机器人控制']
- [api/command.md, '接入API', '自定义命令']
- [api/custombot.md, '接入API', '自定义机器人']

- [doc.md, '文档']
- [doc/formatting.md, '开发文档', '消息格式化']
- [doc/attachments.md, '开发文档', '附加消息内容']


- [resource.md, '资源']
- [resource/community.md, '开发资源', '社区开源项目']
- [resource/support.md, '开发资源', '联系我们']

#theme: readthedocs
theme_dir: 'theme/default'
#theme_dir: 'theme/mkdocs'
docs_dir: 'docs'
site_dir: 'site'